import React from 'react';
import { Scale, FileCheck, Shield, AlertTriangle, Gavel } from 'lucide-react';

export const TermsConditions: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-12">
      <div className="border-b border-[#27272A] pb-6 space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#7C3AED]/10 border border-[#7C3AED]/30 text-xs font-bold text-[#A78BFA]">
          <Scale className="w-3.5 h-3.5 text-[#22D3EE]" />
          <span>Terms of Service Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white">Terms and Conditions</h1>
        <p className="text-xs text-[#A1A1AA]">
          Last Updated: September 23, 2026 | Trade Name: <strong className="text-white">Clippix AI Technologies</strong>
        </p>
      </div>

      <div className="space-y-8 text-xs sm:text-sm text-[#A1A1AA] leading-relaxed">
        <section className="space-y-3 bg-[#18181B] p-6 rounded-2xl border border-[#27272A]">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <FileCheck className="w-4 h-4 text-[#A78BFA]" />
            1. Agreement to Terms
          </h2>
          <p>
            By accessing or using the website and software services provided by <strong className="text-white">Clippix AI Technologies</strong> ("Clippix", "We", "Us"), you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree with any part of these terms, you must not use our website or services.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <Shield className="w-4 h-4 text-[#22D3EE]" />
            2. Description of Service & User Accounts
          </h2>
          <p>
            Clippix provides AI-powered image editing and background removal SaaS software. Users must register for an account to process images, manage credit allocations, and subscribe to paid plans. You are responsible for maintaining the confidentiality of your account credentials.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <Scale className="w-4 h-4 text-[#3B82F6]" />
            3. Intellectual Property Rights & Image Ownership
          </h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              <strong className="text-white">User Image Ownership:</strong> You retain 100% full legal ownership, copyright, and intellectual property rights of all images you upload to Clippix and all background-removed output cutouts generated by our AI engine.
            </li>
            <li>
              <strong className="text-white">Platform Ownership:</strong> The Clippix branding, logo, web design, source code, and AI algorithms remain the exclusive intellectual property of Clippix AI Technologies.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-400" />
            4. Acceptable Use Policy
          </h2>
          <p>
            You agree not to upload images that contain illegal, fraudulent, harmful, or abusive content, or images that infringe upon third-party copyrights or privacy rights.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <Gavel className="w-4 h-4 text-emerald-400" />
            5. Governing Law & Jurisdiction
          </h2>
          <p>
            These Terms and Conditions are governed by and construed in accordance with the laws of <strong className="text-white">India</strong>. Any disputes arising out of or relating to these terms shall be subject to the exclusive jurisdiction of the courts located in <strong className="text-white">Bengaluru, Karnataka, India</strong>.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <FileCheck className="w-4 h-4 text-[#A78BFA]" />
            6. Contact Legal Team
          </h2>
          <div className="p-4 rounded-xl bg-[#09090B] border border-[#27272A] text-xs space-y-1">
            <p><strong className="text-white">Legal Entity Name:</strong> Clippix AI Technologies Pvt Ltd</p>
            <p><strong className="text-white">Email:</strong> legal@clippix.ai / support@clippix.ai</p>
            <p><strong className="text-white">Address:</strong> Outer Ring Road, Bellandur, Bengaluru, Karnataka - 560103, India</p>
          </div>
        </section>
      </div>
    </div>
  );
};
